version: '3.8'

services:
  database:
    container_name: leftovers-postgres
    image: postgres:16.3
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    volumes:
      - postgres-data:/data/postgres
    networks:
      - fullstack-project

networks:
  fullstack-project:
    driver: bridge

volumes:
  postgres-data: